
name: 'Gitbook-Action'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: main
        source_dir: .
        publish_commit_message: ${{ github.event.head_commit.message }}
        publish_branch: gh-pages
        publish_dir: .
